### PR TITLE
Various Python code improvements

### PR DESCRIPTION
**Pull request by AxylumRust**
Several optimizations of the Phyton source code.

### CODE REVIEW

**Review by sockysec — APPROVED** [review]
Thanks a heap, @AxylumRust for the refractor and improvements!

**Comment by AxylumRust** [comment]
You are welcome.

**Comment by sockysec** [comment]
Out of curiosity - a Telerecon user recently reported that their TG account was banned after running userdetails.py . Would any of the changes you made potentially have resulted in this behavior?

**Comment by AxylumRust** [comment]
I don't think so, I just reformatted the code, no more, no less.

**Comment by sockysec** [comment]
Thanks heaps - just thought I would ask to double-check.

**Pull request merged**
