### PR TITLE
Make the scrape process handle more entity 

### PR DESCRIPTION
**Pull request by NeonBubbles**
1. Use subprocess to handle the event loop of every script in launcher.py
2. The entity of post.sender in userscraper.py might be a Channel, and original_message.sender might be a "NoneType"
To avoid the error interrupting the scrape process, use the isinstance function to identify the entity and use the try-except statement to handle the "NoneType" object.

### CODE REVIEW

**Comment by sockysec** [comment]
@NeonBubbles, thanks a bunch for putting work into this, these changes look great. Out of curiosity, have you done much testing of this? Particularly whether the launcher subprocess changes impact any of the other scripts? Additionally, whether the improvements to userscraper.py should also be applied to usermultiscraper.py ?

**Comment by NeonBubbles** [comment]
As long as each script ends normally, the corresponding subprocesses will also shut down, not continuing to occupy system resources. However, I haven't done much testing on them. I will carry out the tests tonight.

**Comment by NeonBubbles** [comment]
The subprocess method is not an excellent way to handle the event loop in your program; the importlib is better but requires more code change. Maybe we can fix them in another PR so I keep the launcher.py unchanged in this PR.
Also, I made the exact change to the usermultiscraper.py as I did to the userscraper.py. And add some private files to .gitignore.
Last, I made some optimizations to setup.py so that it can be used without needing the detailsshell.py file.

I am unfamiliar with Git, so the commit numbers I made might be annoying.  @sockysec

**Comment by sockysec** [comment]
@NeonBubbles thanks for this, this method appears to correctly solve the event looping issue. Did some testing myself and this all looks great. Will merge the request now. Thanks again

**Review by detrixVR — APPROVED** [review]

**Pull request merged**
